on:
  push:
    branches:
      - master

jobs:
  run_pull:
    name: Run Pull on EC2 Server
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Pull Code and Run Script on EC2
        run: |
          ssh -p ${{ secrets.PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo -i && cd ${{ secrets.WORK_DIR }} && git pull && chmod +x ./script.sh && ./script.sh"
